import { describe, it, expect, beforeAll, vi } from "vitest";
import request from "supertest";
import { app, SEED_USERS, SEED_IDS } from "./helpers.js";

// Deterministic AI: force the services' built-in mock engines instead of the
// real Gemini API (avoids 429 quota exhaustion and 30s test timeouts).
vi.mock("../src/services/gemini.service.js", () => ({
  isGeminiConfigured: () => false,
  generateText: async () => "{}",
  generateQuestions: async () => [],
  generateLessonFromContent: async () => ({
    title: "Mock Lesson",
    description: "Mock lesson description",
    content: "Mock content",
    objectives: [],
    keyTerms: [],
    practiceQuestions: [],
  }),
  generateTutorResponse: async () => "Mocked tutor response.",
  analyzeDocument: async () => ({
    summary: "Mock summary",
    keyConcepts: [],
    learningObjectives: [],
    suggestedLessonTitle: "Mock Lesson",
    suggestedCategory: "Fundamentals",
    rawContent: "",
  }),
}));

async function loginAs(role: keyof typeof SEED_USERS): Promise<string> {
  const res = await request(app)
    .post("/api/auth/login")
    .send(SEED_USERS[role]);
  return res.body.data.accessToken;
}

describe("AI Content Module", () => {
  let instructorToken: string;
  let studentToken: string;
  const generatedQuestionIds: string[] = [];

  beforeAll(async () => {
    instructorToken = await loginAs("instructor");
    studentToken = await loginAs("student");
  });

  // Remove rows created by THIS test run so repeated runs don't accumulate
  // (titles are the exact strings the tests insert; the seed uses different titles).
  afterAll(async () => {
    const { db } = await import("../src/database/index.js");
    const { aiGeneratedCases, aiGeneratedStudyGuides, aiGeneratedQuestions, aiContentApprovalHistory } = await import("../src/database/schema/index.js");
    const { eq, inArray } = await import("drizzle-orm");

    // Questions generated by this run (incl. their approval history).
    if (generatedQuestionIds.length > 0) {
      await db.delete(aiContentApprovalHistory).where(inArray(aiContentApprovalHistory.contentId, generatedQuestionIds));
      await db.delete(aiGeneratedQuestions).where(inArray(aiGeneratedQuestions.id, generatedQuestionIds));
    }

    const staleCases = await db.select({ id: aiGeneratedCases.id }).from(aiGeneratedCases)
      .where(eq(aiGeneratedCases.title, "Post-Operative Care Case"));
    const staleGuides = await db.select({ id: aiGeneratedStudyGuides.id }).from(aiGeneratedStudyGuides)
      .where(eq(aiGeneratedStudyGuides.title, "Pharmacology Study Guide"));
    const staleIds = [...staleCases, ...staleGuides].map((r) => r.id);

    if (staleIds.length > 0) {
      await db.delete(aiContentApprovalHistory).where(inArray(aiContentApprovalHistory.contentId, staleIds));
    }
    if (staleCases.length > 0) {
      await db.delete(aiGeneratedCases).where(eq(aiGeneratedCases.title, "Post-Operative Care Case"));
    }
    if (staleGuides.length > 0) {
      await db.delete(aiGeneratedStudyGuides).where(eq(aiGeneratedStudyGuides.title, "Pharmacology Study Guide"));
    }
  });

  describe("Questions", () => {
    let questionId: string;

    it("GET /api/ai-content/questions - should list questions", async () => {
      const res = await request(app)
        .get("/api/ai-content/questions")
        .set("Authorization", `Bearer ${instructorToken}`);

      expect(res.status).toBe(200);
      expect(res.body.success).toBe(true);
    });

    it("POST /api/ai-content/questions/generate - should generate questions (instructor)", async () => {
      const res = await request(app)
        .post("/api/ai-content/questions/generate")
        .set("Authorization", `Bearer ${instructorToken}`)
        .send({
          // Unique per run so the topic+text dedup can never swallow the rows.
          topic: `Cardiovascular Nursing e2e-${Date.now()}`,
          courseId: SEED_IDS.courseId,
          questionType: "MC",
          difficulty: "MEDIUM",
          count: 2,
        });

      expect([200, 201]).toContain(res.status);
      expect(res.body.success).toBe(true);
      expect(Array.isArray(res.body.data)).toBe(true);
      expect(res.body.data.length).toBeGreaterThan(0);
      questionId = res.body.data[0].id;
      generatedQuestionIds.push(...res.body.data.map((q: { id: string }) => q.id));
    });

    it("POST /api/ai-content/questions/generate - should reject student", async () => {
      const res = await request(app)
        .post("/api/ai-content/questions/generate")
        .set("Authorization", `Bearer ${studentToken}`)
        .send({ topic: "Test" });

      expect(res.status).toBe(403);
    });

    it("POST /api/ai-content/questions/:id/review - should return a question for revision with notes", async () => {
      // Review the question THIS run's generate test created — never user data.
      expect(questionId).toBeTruthy();

      const res = await request(app)
        .post(`/api/ai-content/questions/${questionId}/review`)
        .set("Authorization", `Bearer ${instructorToken}`)
        .send({ status: "REVISION_NEEDED", reviewNotes: "Tighten the rationale and verify the correct option" });

      expect(res.status).toBe(200);
      expect(res.body.success).toBe(true);
      expect(res.body.data.status).toBe("REVISION_NEEDED");
      expect(res.body.data.reviewNotes).toBe("Tighten the rationale and verify the correct option");
    });

    it("PUT /api/ai-content/questions/:id - should edit a question returned for revision", async () => {
      const res = await request(app)
        .put(`/api/ai-content/questions/${questionId}`)
        .set("Authorization", `Bearer ${instructorToken}`)
        .send({
          topic: "Cardiovascular Nursing",
          questionText: "Edited: which finding indicates worsening heart failure?",
          options: ["Bounding pulse", "Neck vein distention"],
          correctAnswer: "Neck vein distention",
          explanation: "Elevated JVP reflects right-sided volume overload.",
          difficulty: "HARD",
        });

      expect(res.status).toBe(200);
      expect(res.body.success).toBe(true);
      expect(res.body.data.status).toBe("PENDING");
      expect(res.body.data.questionText).toContain("worsening heart failure");
      expect(res.body.data.correctAnswer).toBe("Neck vein distention");
      expect(res.body.data.difficulty).toBe("HARD");
      expect(res.body.data.version).toBe(2);
      expect(res.body.data.reviewNotes).toBeNull();
    });

    it("PUT /api/ai-content/questions/:id - should reject student", async () => {
      const res = await request(app)
        .put(`/api/ai-content/questions/${questionId}`)
        .set("Authorization", `Bearer ${studentToken}`)
        .send({ questionText: "Student should not edit content" });

      expect(res.status).toBe(403);
    });
  });

  describe("Cases", () => {
    let caseId: string;

    it("GET /api/ai-content/cases - should list cases", async () => {
      const res = await request(app)
        .get("/api/ai-content/cases")
        .set("Authorization", `Bearer ${instructorToken}`);

      expect(res.status).toBe(200);
      expect(res.body.success).toBe(true);
    });

    it("POST /api/ai-content/cases/generate - should generate a case (instructor)", async () => {
      const res = await request(app)
        .post("/api/ai-content/cases/generate")
        .set("Authorization", `Bearer ${instructorToken}`)
        .send({
          title: "Post-Operative Care Case",
          courseId: SEED_IDS.courseId,
          difficulty: "MEDIUM",
          focusArea: "Surgical Nursing",
        });

      expect([200, 201]).toContain(res.status);
      expect(res.body.success).toBe(true);
      caseId = res.body.data.id;
      expect(caseId).toBeTruthy();
    });

    it("PUT /api/ai-content/cases/:id - should edit a pending case", async () => {
      const res = await request(app)
        .put(`/api/ai-content/cases/${caseId}`)
        .set("Authorization", `Bearer ${instructorToken}`)
        .send({
          title: "Post-Operative Care Case",
          description: "Edited: 45-year-old post-appendectomy patient with escalating pain scores.",
          clinicalPresentation: "Edited: pain 8/10 with guarding and tachycardia.",
          difficulty: "HARD",
          stages: [{ stage: 1, description: "Reassess pain and escalate analgesic efficacy" }],
          learningObjectives: ["Edited: escalate findings when analgesia is ineffective"],
        });

      expect(res.status).toBe(200);
      expect(res.body.success).toBe(true);
      expect(res.body.data.status).toBe("PENDING");
      expect(res.body.data.stages[0].description).toContain("Reassess pain");
      expect(res.body.data.learningObjectives[0]).toContain("escalate findings");
      expect(res.body.data.version).toBe(2);
    });

    it("POST /api/ai-content/cases/:id/review - should approve a case (instructor)", async () => {
      const res = await request(app)
        .post(`/api/ai-content/cases/${caseId}/review`)
        .set("Authorization", `Bearer ${instructorToken}`)
        .send({ status: "APPROVED", reviewNotes: "Clinically accurate" });

      expect(res.status).toBe(200);
      expect(res.body.success).toBe(true);
      expect(res.body.data.status).toBe("APPROVED");
    });

    it("PUT /api/ai-content/cases/:id - should return 409 once approved", async () => {
      const res = await request(app)
        .put(`/api/ai-content/cases/${caseId}`)
        .set("Authorization", `Bearer ${instructorToken}`)
        .send({ description: "Approved content must stay immutable" });

      expect(res.status).toBe(409);
      expect(res.body.error.message).toContain("no longer be edited");
    });

    it("POST /api/ai-content/cases/:id/review - should reject student", async () => {
      const res = await request(app)
        .post(`/api/ai-content/cases/${caseId}/review`)
        .set("Authorization", `Bearer ${studentToken}`)
        .send({ status: "REJECTED" });

      expect(res.status).toBe(403);
    });
  });

  describe("Study Guides", () => {
    let guideId: string;

    it("GET /api/ai-content/study-guides - should list study guides", async () => {
      const res = await request(app)
        .get("/api/ai-content/study-guides")
        .set("Authorization", `Bearer ${instructorToken}`);

      expect(res.status).toBe(200);
      expect(res.body.success).toBe(true);
    });

    it("POST /api/ai-content/study-guides/generate - should generate a study guide (instructor)", async () => {
      const res = await request(app)
        .post("/api/ai-content/study-guides/generate")
        .set("Authorization", `Bearer ${instructorToken}`)
        .send({
          title: "Pharmacology Study Guide",
          topic: "Antihypertensive Medications",
          courseId: SEED_IDS.courseId,
          includePracticeQuestions: true,
        });

      expect([200, 201]).toContain(res.status);
      expect(res.body.success).toBe(true);
      guideId = res.body.data.id;
      expect(guideId).toBeTruthy();
    });

    it("PUT /api/ai-content/study-guides/:id - should edit a pending study guide", async () => {
      const res = await request(app)
        .put(`/api/ai-content/study-guides/${guideId}`)
        .set("Authorization", `Bearer ${instructorToken}`)
        .send({
          title: "Pharmacology Study Guide",
          content: "# Edited Pharmacology Guide\n\n## Key Points\n- Narrow therapeutic index drugs",
          summary: "Edited summary with safer medication administration focus.",
          keyPoints: ["Edited: verify therapeutic drug levels", "Edited: monitor for toxicity signs"],
        });

      expect(res.status).toBe(200);
      expect(res.body.success).toBe(true);
      expect(res.body.data.status).toBe("PENDING");
      expect(res.body.data.content).toContain("Edited Pharmacology Guide");
      expect(res.body.data.keyPoints).toHaveLength(2);
      expect(res.body.data.version).toBe(2);
    });

    it("POST /api/ai-content/study-guides/:id/review - should reject a study guide (instructor)", async () => {
      const res = await request(app)
        .post(`/api/ai-content/study-guides/${guideId}/review`)
        .set("Authorization", `Bearer ${instructorToken}`)
        .send({ status: "REJECTED", reviewNotes: "Needs citations" });

      expect(res.status).toBe(200);
      expect(res.body.success).toBe(true);
      expect(res.body.data.status).toBe("REJECTED");
    });

    it("PUT /api/ai-content/study-guides/:id - should return 409 once rejected", async () => {
      const res = await request(app)
        .put(`/api/ai-content/study-guides/${guideId}`)
        .set("Authorization", `Bearer ${instructorToken}`)
        .send({ content: "Rejected content must stay immutable" });

      expect(res.status).toBe(409);
      expect(res.body.error.message).toContain("no longer be edited");
    });
  });

  describe("Approval History", () => {
    it("GET /api/ai-content/approval-history/:contentType/:contentId - should return history", async () => {
      const res = await request(app)
        .get(`/api/ai-content/approval-history/question/00000000-0000-0000-0000-000000000000`)
        .set("Authorization", `Bearer ${instructorToken}`);

      expect(res.status).toBe(200);
      expect(res.body.success).toBe(true);
    });
  });
});
